/** With Bible table names (wb_ prefix in shared Supabase) */
export const Tables = {
  profiles: 'wb_profiles',
  classes: 'wb_classes',
  projects: 'wb_projects',
  projectClasses: 'wb_project_classes',
  projectTargets: 'wb_project_targets',
  bibleBooks: 'wb_bible_books',
  readingLogs: 'wb_reading_logs',
  encouragements: 'wb_encouragements',
  announcements: 'wb_announcements',
  comments: 'wb_comments',
  staffCodes: 'wb_staff_codes',
  readAlongs: 'wb_read_alongs',
  notifications: 'wb_notifications',
  feedback: 'wb_feedback',
  chatterPosts: 'wb_chatter_posts',
  chatterComments: 'wb_chatter_comments',
  chatterReactions: 'wb_chatter_reactions',
  chatterReports: 'wb_chatter_reports',
  playgroundContents: 'wb_playground_contents',
  playgroundHistory: 'wb_playground_history',
  playgroundResponses: 'wb_playground_responses',
} as const
